### ISSUE TITLE
Compile error: 'class HM1X_BT' has no member named 'begin'

### ISSUE THREAD

**Issue by semanel** [sparkfun/SparkFun_HM1X_Bluetooth_Arduino_Library#1]
Cannot compile either of the examples because of the following error:

Arduino: 1.8.5 (Windows 7), Board: "SparkFun Pro Micro, ATmega32U4 (3.3V, 8 MHz)"

C:\Arduino\libraries\SparkFun_HM1X_Bluetooth_Arduino_Library\examples\HardwareSerial_01_Passthrough\HardwareSerial_01_Passthrough.ino: In function 'void setup()':

HardwareSerial_01_Passthrough:43: error: 'class HM1X_BT' has no member named 'begin'

   if (bt.begin(Serial1, 9600) == false) {

exit status 1
'class HM1X_BT' has no member named 'begin'

**Comment by jimblom** [comment]
Good catch! I hadn't tried this library on a Pro Micro yet.

I just pushed a few changes in this commit: [https://github.com/sparkfun/SparkFun_HM1X_Bluetooth_Arduino_Library/commit/838cd21f23e174cba66afc7ff1861fd825666972](https://github.com/sparkfun/SparkFun_HM1X_Bluetooth_Arduino_Library/commit/838cd21f23e174cba66afc7ff1861fd825666972). It compiles now, but I haven't had a chance to test it out yet. Let me know if it works for you.

**Comment by semanel** [comment]
Tested on the Pro Micro and it works

Thanks!

**Comment by jimblom** [comment]
Awesome. Thanks!

**Comment by akrv** [comment]
https://community.blynk.cc/t/solved-blynk-and-ble-using-hm10-module-ok-conn-problem/20172/4
I used the code from this link, the BT module replies.

when i test SoftwareSerial_02_Poll_Passthrough example

```
test_SoftwareSerial_02_Poll_Passthrough:47: error: 'class HM1X_BT' has no member named 'begin'
   if (bt.begin(hm13Serial, 9600) == false) {
          ^
'class HM1X_BT' has no member named 'begin'
```

board is teensy 3.6
pins are 0,1 

how can i make it work?
